### ISSUE TITLE
Is http.Request in lambda has extral cost, like network or something else?

### ISSUE THREAD

**Issue by kaixinbuyu** [MarcelloLins/ServerlessCrawler-VancouverRealState#6]
1.is there othere costs like network request?what.s the total cost?
2.can lambda chang ip when every exec ?

**Comment by MarcelloLins** [comment]
1 - No, there are no extra costs on Lambda for network outbound calls AFAICT.

2 - There's no option to do something like this. Have in mind that something like lambda is only as attractive as it is, because it is probably able to keep some containers "warm" allowing for re-use reducing it's spin up time. Hence, these containers will all have the pool of IPS.

**Comment by kaixinbuyu** [comment]
Thank you very match!
